baseurl = "http://uhtec.com/"
languageCode = "en-us"
title = "UHTec"
googleAnalytics = "UA-73436304-1"
disqusShortname = "UHTec"
[params]
name = "Ulrich HÃ¶lscher"
email = "blog@uhtec.com"
twitter = "https://twitter.com/DevUlrix"
github = "https://github.com/devulrix"
frontpageposts = 5
copyrightyear = "2016"
